#!/bin/bash

word=$1
reverse=""

for (( i=${#word}-1; i>=0; i-- ))
do
    reverse="$reverse${word:$i:1}"
done

if [ $word = $reverse ]
then
    echo "$word es una palabra palíndroma"
else
    echo "$word no es una palabra palíndroma"
fi
