#!/bin/bash
echo "Introduce un número"
read num
	if  ! expr "$num" + 1 >/dev/null 2>&1
	then
		echo "No has introducido un número"
	else
		echo "La tabla de multiplicar escrita de forma inversa  del $num es:"

		for ((i=10; i>=0; i--)); 
			do
				resultado=$((num * i))
				echo "$num x $i = $resultado"
			done
	fi
